# Generated by Grammarinator 26.1

from math import inf
from typing import Callable, ClassVar
from grammarinator.runtime import *

class urlGenerator(Generator):


    def url(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'url', parent) as rule:
            current = rule.current
            self.uri(parent=current)
        return current

    def uri(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'uri', parent) as rule:
            current = rule.current
            self._reserve(6, self.protocol, parent=current)
            self._reserve(5, self.T__0, parent=current)
            self._reserve(4, self.host, parent=current)
            self._reserve(3, self.T__1, parent=current)
            self._reserve(2, self.port, parent=current)
            self._reserve(1, self.T__2, parent=current)
            self.query(parent=current)
        return current

    def protocol(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'protocol', parent) as rule:
            current = rule.current
            self.PROTOCOL(parent=current)
        return current

    def host(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'host', parent) as rule:
            current = rule.current
            self.HOSTNAME(parent=current)
        return current

    def port(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'port', parent) as rule:
            current = rule.current
            self.PORTS(parent=current)
        return current

    def query(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'query', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, urlGenerator._alt_sizes[2], 0, urlGenerator._alt_conds[2]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    self.CITY(parent=current)
                elif choice0 == 1:
                    self._reserve(1, self.CITY, parent=current)
                    self.T__3(parent=current)
                elif choice0 == 2:
                    self._reserve(4, self.CITY, parent=current)
                    self._reserve(3, self.T__4, parent=current)
                    self.search(parent=current)
                elif choice0 == 3:
                    self._reserve(5, self.CITY, parent=current)
                    self._reserve(4, self.T__3, parent=current)
                    self._reserve(3, self.T__4, parent=current)
                    self.search(parent=current)
            current = rule.current
        return current

    def search(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'search', parent) as rule:
            current = rule.current
            self.searchparameter(parent=current)
        return current

    def searchparameter(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'searchparameter', parent) as rule:
            current = rule.current
            self._reserve(2, self.T__5, parent=current)
            self._reserve(1, self.T__6, parent=current)
            with AlternationContext(rule, 0, urlGenerator._alt_sizes[3], 0, urlGenerator._alt_conds[3]) as alt0:
                current = rule.current
                [self.T__7, self.T__8, self.T__9, self.T__10, self.T__11, self.T__12][alt0()](parent=current)
            current = rule.current
        return current

    def QUOTED_STRING(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'QUOTED_STRING', parent) as rule:
            current = rule.current
            current.src += '\''
            with QuantifierContext(rule, 0, 0, inf, urlGenerator._quant_sizes[0], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        current.src += self._model.charset(current, 0, urlGenerator._charsets[1])
            current = rule.current
            current.src += '\''
        return current

    def string(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'string', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, urlGenerator._alt_sizes[4], 0, urlGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.STRING, self.DIGITS][alt0()](parent=current)
            current = rule.current
        return current

    def DIGITS(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'DIGITS', parent) as rule:
            current = rule.current
            with QuantifierContext(rule, 0, 1, inf, urlGenerator._quant_sizes[0], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        current.src += self._model.charset(current, 0, urlGenerator._charsets[2])
            current = rule.current
        return current

    def HEX(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'HEX', parent) as rule:
            current = rule.current
            with QuantifierContext(rule, 0, 1, inf, urlGenerator._quant_sizes[0], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        current.src += '%'
                        current.src += self._model.charset(current, 0, urlGenerator._charsets[3])
                        current.src += self._model.charset(current, 1, urlGenerator._charsets[3])
            current = rule.current
        return current

    def STRING(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'STRING', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, urlGenerator._alt_sizes[0], 0, urlGenerator._alt_conds[0]) as alt0:
                current = rule.current
                choice0 = alt0()
                if choice0 == 0:
                    current.src += self._model.charset(current, 0, urlGenerator._charsets[4])
                elif choice0 == 1:
                    self.HEX(parent=current)
            current = rule.current
            with QuantifierContext(rule, 0, 0, inf, urlGenerator._quant_sizes[0], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        with AlternationContext(rule, 1, urlGenerator._alt_sizes[0], 0, urlGenerator._alt_conds[0]) as alt1:
                            current = rule.current
                            choice1 = alt1()
                            if choice1 == 0:
                                current.src += self._model.charset(current, 1, urlGenerator._charsets[5])
                            elif choice1 == 1:
                                self.HEX(parent=current)
                        current = rule.current
            current = rule.current
        return current

    def PROTOCOL(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'PROTOCOL', parent, True) as rule:
            current = rule.current
            current.src += 'http'
        return current

    def HOSTNAME(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'HOSTNAME', parent, True) as rule:
            current = rule.current
            current.src += 'localhost'
        return current

    def PORTS(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'PORTS', parent, True) as rule:
            current = rule.current
            current.src += '8002'
        return current

    def CITY(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'CITY', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, urlGenerator._alt_sizes[1], 0, urlGenerator._alt_conds[1]) as alt0:
                current = rule.current
                current.src += ['cairo', 'paris', 'london', 'tokyo', 'berlin', 'madrid', 'dubai', 'singapore', 'bangkok', 'beijing', 'sydney', 'newyork', 'losangeles', 'rome', 'moscow', 'seoul', 'new-york', 'los-angeles', 'delhi', 'hongkong', 'istanbul', 'riyadh', 'toronto'][alt0()]
            current = rule.current
        return current

    def T__0(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__0', parent, True) as rule:
            current = rule.current
            current.src += '://'
        return current

    def T__1(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__1', parent, True) as rule:
            current = rule.current
            current.src += ':'
        return current

    def T__2(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__2', parent, True) as rule:
            current = rule.current
            current.src += '/'
        return current

    def T__3(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__3', parent, True) as rule:
            current = rule.current
            current.src += '.png'
        return current

    def T__4(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__4', parent, True) as rule:
            current = rule.current
            current.src += '?'
        return current

    def T__5(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__5', parent, True) as rule:
            current = rule.current
            current.src += 'format'
        return current

    def T__6(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__6', parent, True) as rule:
            current = rule.current
            current.src += '='
        return current

    def T__7(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__7', parent, True) as rule:
            current = rule.current
            current.src += 'j1'
        return current

    def T__8(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__8', parent, True) as rule:
            current = rule.current
            current.src += 'j2'
        return current

    def T__9(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__9', parent, True) as rule:
            current = rule.current
            current.src += 'p1'
        return current

    def T__10(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__10', parent, True) as rule:
            current = rule.current
            current.src += 'v2'
        return current

    def T__11(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__11', parent, True) as rule:
            current = rule.current
            current.src += 'v2d'
        return current

    def T__12(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__12', parent, True) as rule:
            current = rule.current
            current.src += 'v2n'
        return current


    _default_rule: ClassVar[Callable[['urlGenerator', ParentRule | None], Rule]] = url

    _rule_sizes: ClassVar[dict[str, RuleSize]] = {
        'url': RuleSize(4, 7),
        'uri': RuleSize(3, 7),
        'protocol': RuleSize(2, 1),
        'host': RuleSize(2, 1),
        'port': RuleSize(2, 1),
        'query': RuleSize(2, 1),
        'search': RuleSize(3, 3),
        'searchparameter': RuleSize(2, 3),
        'QUOTED_STRING': RuleSize(1, 1),
        'string': RuleSize(2, 1),
        'DIGITS': RuleSize(1, 1),
        'HEX': RuleSize(1, 1),
        'STRING': RuleSize(1, 1),
        'PROTOCOL': RuleSize(1, 1),
        'HOSTNAME': RuleSize(1, 1),
        'PORTS': RuleSize(1, 1),
        'CITY': RuleSize(1, 1),
        'T__0': RuleSize(1, 1),
        'T__1': RuleSize(1, 1),
        'T__2': RuleSize(1, 1),
        'T__3': RuleSize(1, 1),
        'T__4': RuleSize(1, 1),
        'T__5': RuleSize(1, 1),
        'T__6': RuleSize(1, 1),
        'T__7': RuleSize(1, 1),
        'T__8': RuleSize(1, 1),
        'T__9': RuleSize(1, 1),
        'T__10': RuleSize(1, 1),
        'T__11': RuleSize(1, 1),
        'T__12': RuleSize(1, 1),
    }

    _alt_sizes: ClassVar[tuple[tuple[RuleSize, ...], ...]] = (
        (RuleSize(0, 0), RuleSize(1, 1)),  # 0
        (RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0), RuleSize(0, 0)),  # 1
        (RuleSize(1, 1), RuleSize(1, 2), RuleSize(3, 5), RuleSize(3, 6)),  # 2
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 3
        (RuleSize(1, 1), RuleSize(1, 1)),  # 4
    )

    _alt_conds: ClassVar[tuple[tuple[float, ...], ...]] = (
        (1, 1),  # 0
        (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),  # 1
        (1, 1, 1, 1),  # 2
        (1, 1, 1, 1, 1, 1),  # 3
    )

    _quant_sizes: ClassVar[tuple[RuleSize, ...]] = (
        RuleSize(0, 0),  # 0
    )

    _charsets: ClassVar[tuple[tuple[int, ...], ...]] = (
        Generator._charset(((0x20, 0x7f), )),  # 0
        Generator._charset(((0x20, 0x27), (0x28, 0x7f), )),  # 1
        Generator._charset(((0x30, 0x3a), )),  # 2
        Generator._charset(((0x30, 0x3a), (0x41, 0x47), (0x61, 0x67), )),  # 3
        Generator._charset(((0x30, 0x3a), (0x41, 0x5b), (0x61, 0x7b), (0x7e, 0x7f), )),  # 4
        Generator._charset(((0x2b, 0x2c), (0x2d, 0x2e), (0x2e, 0x2f), (0x30, 0x3a), (0x41, 0x5b), (0x61, 0x7b), )),  # 5
    )
