# Generated by Grammarinator 26.1

from math import inf
from typing import Callable, ClassVar
from grammarinator.runtime import *

class httpGenerator(Generator):


    def http_message(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'http_message', parent) as rule:
            current = rule.current
            self.start_line(parent=current)
            with QuantifierContext(rule, 0, 0, inf, httpGenerator._quant_sizes[0], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        self._reserve(1, self.header_field, parent=current)
                        self.CRLF(parent=current)
            current = rule.current
        return current

    def start_line(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'start_line', parent) as rule:
            current = rule.current
            self.request_line(parent=current)
        return current

    def request_line(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'request_line', parent) as rule:
            current = rule.current
            self._reserve(9, self.method, parent=current)
            self._reserve(8, self.SP, parent=current)
            self._reserve(7, self.request_target, parent=current)
            self._reserve(6, self.SP, parent=current)
            self._reserve(1, self.http_version, parent=current)
            self.CRLF(parent=current)
        return current

    def method(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'method', parent) as rule:
            current = rule.current
            self.token(parent=current)
        return current

    def request_target(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'request_target', parent) as rule:
            current = rule.current
            self.origin_form(parent=current)
        return current

    def origin_form(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'origin_form', parent) as rule:
            current = rule.current
            self.absolute_path(parent=current)
            with QuantifierContext(rule, 0, 0, 1, httpGenerator._quant_sizes[1], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        self.QUESTION_MARK(parent=current)
                        self.query(parent=current)
            current = rule.current
        return current

    def absolute_path(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'absolute_path', parent) as rule:
            current = rule.current
            with QuantifierContext(rule, 0, 1, inf, httpGenerator._quant_sizes[1], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        self.SLASH(parent=current)
                        self.segment(parent=current)
            current = rule.current
        return current

    def segment(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'segment', parent) as rule:
            current = rule.current
            with QuantifierContext(rule, 0, 0, inf, httpGenerator._quant_sizes[2], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        self.pchar(parent=current)
            current = rule.current
        return current

    def query(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'query', parent) as rule:
            current = rule.current
            with QuantifierContext(rule, 0, 0, inf, httpGenerator._quant_sizes[1], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        with AlternationContext(rule, 0, httpGenerator._alt_sizes[1], 0, httpGenerator._alt_conds[1]) as alt0:
                            current = rule.current
                            [self.pchar, self.SLASH, self.QUESTION_MARK][alt0()](parent=current)
                        current = rule.current
            current = rule.current
        return current

    def http_version(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'http_version', parent) as rule:
            current = rule.current
            self._reserve(4, self.T__0, parent=current)
            self._reserve(3, self.SLASH, parent=current)
            self._reserve(2, self.DIGIT, parent=current)
            self._reserve(1, self.DOT, parent=current)
            self.DIGIT(parent=current)
        return current

    def header_field(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'header_field', parent) as rule:
            current = rule.current
            self._reserve(1, self.field_name, parent=current)
            self.COLON(parent=current)
            self.ows(parent=current)
            self.field_value(parent=current)
            self.ows(parent=current)
        return current

    def field_name(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'field_name', parent) as rule:
            current = rule.current
            self.token(parent=current)
        return current

    def token(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'token', parent) as rule:
            current = rule.current
            with QuantifierContext(rule, 0, 1, inf, httpGenerator._quant_sizes[2], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        self.tchar(parent=current)
            current = rule.current
        return current

    def tchar(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'tchar', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, httpGenerator._alt_sizes[2], 0, httpGenerator._alt_conds[2]) as alt0:
                current = rule.current
                [self.EXCLAMATION_MARK, self.DOLLAR_SIGN, self.HASHTAG, self.PERCENT, self.AMPERSAND, self.SQUOTE, self.STAR, self.PLUS, self.MINUS, self.DOT, self.CARET, self.UNDERSCORE, self.BACK_QUOTE, self.VBAR, self.TILDE, self.DIGIT, self.HEX_LETTER, self.ALPHA][alt0()](parent=current)
            current = rule.current
        return current

    def field_value(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'field_value', parent) as rule:
            current = rule.current
            with QuantifierContext(rule, 0, 0, inf, httpGenerator._quant_sizes[2], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        with AlternationContext(rule, 0, httpGenerator._alt_sizes[3], 0, httpGenerator._alt_conds[0]) as alt0:
                            current = rule.current
                            [self.field_content, self.obs_fold][alt0()](parent=current)
                        current = rule.current
            current = rule.current
        return current

    def field_content(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'field_content', parent) as rule:
            current = rule.current
            self.field_vchar(parent=current)
            with QuantifierContext(rule, 0, 0, inf, httpGenerator._quant_sizes[3], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        with QuantifierContext(rule, 1, 1, inf, httpGenerator._quant_sizes[1], 1) as quant1:
                            while quant1():
                                with QuantifiedContext(rule):
                                    current = rule.current
                                    with AlternationContext(rule, 0, httpGenerator._alt_sizes[4], 0, httpGenerator._alt_conds[0]) as alt0:
                                        current = rule.current
                                        [self.SP, self.HTAB][alt0()](parent=current)
                                    current = rule.current
                        current = rule.current
                        self.field_vchar(parent=current)
            current = rule.current
        return current

    def ows(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'ows', parent) as rule:
            current = rule.current
            with QuantifierContext(rule, 0, 0, inf, httpGenerator._quant_sizes[1], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        with AlternationContext(rule, 0, httpGenerator._alt_sizes[4], 0, httpGenerator._alt_conds[0]) as alt0:
                            current = rule.current
                            [self.SP, self.HTAB][alt0()](parent=current)
                        current = rule.current
            current = rule.current
        return current

    def field_vchar(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'field_vchar', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, httpGenerator._alt_sizes[5], 0, httpGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.vchar, self.obs_text][alt0()](parent=current)
            current = rule.current
        return current

    def obs_text(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'obs_text', parent) as rule:
            current = rule.current
            self.OBS_TEXT(parent=current)
        return current

    def obs_fold(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'obs_fold', parent) as rule:
            current = rule.current
            self._reserve(1, self.CRLF, parent=current)
            with QuantifierContext(rule, 0, 1, inf, httpGenerator._quant_sizes[1], 0) as quant0:
                while quant0():
                    with QuantifiedContext(rule):
                        current = rule.current
                        with AlternationContext(rule, 0, httpGenerator._alt_sizes[4], 0, httpGenerator._alt_conds[0]) as alt0:
                            current = rule.current
                            [self.SP, self.HTAB][alt0()](parent=current)
                        current = rule.current
            current = rule.current
        return current

    def pchar(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'pchar', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, httpGenerator._alt_sizes[6], 0, httpGenerator._alt_conds[3]) as alt0:
                current = rule.current
                [self.unreserved, self.pct_encoded, self.sub_delims, self.hexdig, self.COLON, self.AT][alt0()](parent=current)
            current = rule.current
        return current

    def pct_encoded(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'pct_encoded', parent) as rule:
            current = rule.current
            self._reserve(2, self.PERCENT, parent=current)
            self._reserve(1, self.hexdig, parent=current)
            self.hexdig(parent=current)
        return current

    def hexdig(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'hexdig', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, httpGenerator._alt_sizes[4], 0, httpGenerator._alt_conds[0]) as alt0:
                current = rule.current
                [self.DIGIT, self.HEX_LETTER][alt0()](parent=current)
            current = rule.current
        return current

    def unreserved(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'unreserved', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, httpGenerator._alt_sizes[7], 0, httpGenerator._alt_conds[3]) as alt0:
                current = rule.current
                [self.ALPHA, self.DIGIT, self.MINUS, self.DOT, self.UNDERSCORE, self.TILDE][alt0()](parent=current)
            current = rule.current
        return current

    def sub_delims(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'sub_delims', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, httpGenerator._alt_sizes[8], 0, httpGenerator._alt_conds[4]) as alt0:
                current = rule.current
                [self.EXCLAMATION_MARK, self.DOLLAR_SIGN, self.AMPERSAND, self.SQUOTE, self.LCOLUMN, self.RCOLUMN, self.STAR, self.PLUS, self.PERIOD, self.SEMICOLON, self.EQUALS][alt0()](parent=current)
            current = rule.current
        return current

    def vchar(self, parent: ParentRule | None = None) -> Rule:
        with UnparserRuleContext(self, 'vchar', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, httpGenerator._alt_sizes[9], 0, httpGenerator._alt_conds[5]) as alt0:
                current = rule.current
                [self.LCOLUMN, self.RCOLUMN, self.SEMICOLON, self.EQUALS, self.PERIOD, self.MINUS, self.DOT, self.UNDERSCORE, self.TILDE, self.QUESTION_MARK, self.SLASH, self.EXCLAMATION_MARK, self.COLON, self.AT, self.DOLLAR_SIGN, self.HASHTAG, self.AMPERSAND, self.PERCENT, self.SQUOTE, self.STAR, self.PLUS, self.CARET, self.BACK_QUOTE, self.VBAR, self.HEX_LETTER, self.ALPHA, self.DIGIT, self.VCHAR][alt0()](parent=current)
            current = rule.current
        return current

    def LCOLUMN(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'LCOLUMN', parent, True) as rule:
            current = rule.current
            current.src += '('
        return current

    def RCOLUMN(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'RCOLUMN', parent, True) as rule:
            current = rule.current
            current.src += ')'
        return current

    def SEMICOLON(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'SEMICOLON', parent, True) as rule:
            current = rule.current
            current.src += ';'
        return current

    def EQUALS(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'EQUALS', parent, True) as rule:
            current = rule.current
            current.src += '='
        return current

    def PERIOD(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'PERIOD', parent, True) as rule:
            current = rule.current
            current.src += ','
        return current

    def MINUS(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'MINUS', parent, True) as rule:
            current = rule.current
            current.src += '-'
        return current

    def DOT(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'DOT', parent, True) as rule:
            current = rule.current
            current.src += '.'
        return current

    def UNDERSCORE(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'UNDERSCORE', parent, True) as rule:
            current = rule.current
            current.src += '_'
        return current

    def TILDE(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'TILDE', parent, True) as rule:
            current = rule.current
            current.src += '~'
        return current

    def QUESTION_MARK(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'QUESTION_MARK', parent, True) as rule:
            current = rule.current
            current.src += '?'
        return current

    def SLASH(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'SLASH', parent, True) as rule:
            current = rule.current
            current.src += '/'
        return current

    def EXCLAMATION_MARK(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'EXCLAMATION_MARK', parent, True) as rule:
            current = rule.current
            current.src += '!'
        return current

    def COLON(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'COLON', parent, True) as rule:
            current = rule.current
            current.src += ':'
        return current

    def AT(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'AT', parent, True) as rule:
            current = rule.current
            current.src += '@'
        return current

    def DOLLAR_SIGN(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'DOLLAR_SIGN', parent, True) as rule:
            current = rule.current
            current.src += '$'
        return current

    def HASHTAG(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'HASHTAG', parent, True) as rule:
            current = rule.current
            current.src += '#'
        return current

    def AMPERSAND(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'AMPERSAND', parent, True) as rule:
            current = rule.current
            current.src += '&'
        return current

    def PERCENT(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'PERCENT', parent, True) as rule:
            current = rule.current
            current.src += '%'
        return current

    def SQUOTE(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'SQUOTE', parent, True) as rule:
            current = rule.current
            current.src += '\''
        return current

    def STAR(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'STAR', parent, True) as rule:
            current = rule.current
            current.src += '*'
        return current

    def PLUS(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'PLUS', parent, True) as rule:
            current = rule.current
            current.src += '+'
        return current

    def CARET(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'CARET', parent, True) as rule:
            current = rule.current
            current.src += '^'
        return current

    def BACK_QUOTE(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'BACK_QUOTE', parent, True) as rule:
            current = rule.current
            current.src += '`'
        return current

    def VBAR(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'VBAR', parent, True) as rule:
            current = rule.current
            current.src += '|'
        return current

    def DIGIT(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'DIGIT', parent) as rule:
            current = rule.current
            current.src += self._model.charset(current, 0, httpGenerator._charsets[1])
        return current

    def HEX_LETTER(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'HEX_LETTER', parent) as rule:
            current = rule.current
            current.src += self._model.charset(current, 0, httpGenerator._charsets[2])
        return current

    def ALPHA(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'ALPHA', parent) as rule:
            current = rule.current
            current.src += self._model.charset(current, 0, httpGenerator._charsets[3])
        return current

    def VCHAR(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'VCHAR', parent) as rule:
            current = rule.current
            current.src += self._model.charset(current, 0, httpGenerator._charsets[4])
        return current

    def OBS_TEXT(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'OBS_TEXT', parent) as rule:
            current = rule.current
            current.src += self._model.charset(current, 0, httpGenerator._charsets[5])
        return current

    def SP(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'SP', parent, True) as rule:
            current = rule.current
            current.src += ' '
        return current

    def HTAB(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'HTAB', parent, True) as rule:
            current = rule.current
            current.src += '\t'
        return current

    def CRLF(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'CRLF', parent) as rule:
            current = rule.current
            with AlternationContext(rule, 0, httpGenerator._alt_sizes[0], 0, httpGenerator._alt_conds[0]) as alt0:
                current = rule.current
                current.src += ['\r\n', '\n'][alt0()]
            current = rule.current
        return current

    def T__0(self, parent: ParentRule | None = None) -> Rule:
        with UnlexerRuleContext(self, 'T__0', parent, True) as rule:
            current = rule.current
            current.src += 'HTTP'
        return current


    _default_rule: ClassVar[Callable[['httpGenerator', ParentRule | None], Rule]] = http_message

    _rule_sizes: ClassVar[dict[str, RuleSize]] = {
        'http_message': RuleSize(7, 10),
        'start_line': RuleSize(6, 10),
        'request_line': RuleSize(5, 10),
        'method': RuleSize(4, 1),
        'request_target': RuleSize(4, 1),
        'origin_form': RuleSize(3, 1),
        'absolute_path': RuleSize(2, 1),
        'segment': RuleSize(1, 0),
        'query': RuleSize(1, 0),
        'http_version': RuleSize(2, 5),
        'header_field': RuleSize(5, 2),
        'field_name': RuleSize(4, 1),
        'token': RuleSize(3, 1),
        'tchar': RuleSize(2, 1),
        'field_value': RuleSize(1, 0),
        'field_content': RuleSize(4, 1),
        'ows': RuleSize(1, 0),
        'field_vchar': RuleSize(3, 1),
        'obs_text': RuleSize(2, 1),
        'obs_fold': RuleSize(2, 2),
        'pchar': RuleSize(2, 1),
        'pct_encoded': RuleSize(3, 3),
        'hexdig': RuleSize(2, 1),
        'unreserved': RuleSize(2, 1),
        'sub_delims': RuleSize(2, 1),
        'vchar': RuleSize(2, 1),
        'LCOLUMN': RuleSize(1, 1),
        'RCOLUMN': RuleSize(1, 1),
        'SEMICOLON': RuleSize(1, 1),
        'EQUALS': RuleSize(1, 1),
        'PERIOD': RuleSize(1, 1),
        'MINUS': RuleSize(1, 1),
        'DOT': RuleSize(1, 1),
        'UNDERSCORE': RuleSize(1, 1),
        'TILDE': RuleSize(1, 1),
        'QUESTION_MARK': RuleSize(1, 1),
        'SLASH': RuleSize(1, 1),
        'EXCLAMATION_MARK': RuleSize(1, 1),
        'COLON': RuleSize(1, 1),
        'AT': RuleSize(1, 1),
        'DOLLAR_SIGN': RuleSize(1, 1),
        'HASHTAG': RuleSize(1, 1),
        'AMPERSAND': RuleSize(1, 1),
        'PERCENT': RuleSize(1, 1),
        'SQUOTE': RuleSize(1, 1),
        'STAR': RuleSize(1, 1),
        'PLUS': RuleSize(1, 1),
        'CARET': RuleSize(1, 1),
        'BACK_QUOTE': RuleSize(1, 1),
        'VBAR': RuleSize(1, 1),
        'DIGIT': RuleSize(1, 1),
        'HEX_LETTER': RuleSize(1, 1),
        'ALPHA': RuleSize(1, 1),
        'VCHAR': RuleSize(1, 1),
        'OBS_TEXT': RuleSize(1, 1),
        'SP': RuleSize(1, 1),
        'HTAB': RuleSize(1, 1),
        'CRLF': RuleSize(1, 1),
        'T__0': RuleSize(1, 1),
    }

    _alt_sizes: ClassVar[tuple[tuple[RuleSize, ...], ...]] = (
        (RuleSize(0, 0), RuleSize(0, 0)),  # 0
        (RuleSize(2, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 1
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 2
        (RuleSize(4, 1), RuleSize(2, 2)),  # 3
        (RuleSize(1, 1), RuleSize(1, 1)),  # 4
        (RuleSize(2, 1), RuleSize(2, 1)),  # 5
        (RuleSize(2, 1), RuleSize(3, 3), RuleSize(2, 1), RuleSize(2, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 6
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 7
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 8
        (RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1), RuleSize(1, 1)),  # 9
    )

    _alt_conds: ClassVar[tuple[tuple[float, ...], ...]] = (
        (1, 1),  # 0
        (1, 1, 1),  # 1
        (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),  # 2
        (1, 1, 1, 1, 1, 1),  # 3
        (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),  # 4
        (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1),  # 5
    )

    _quant_sizes: ClassVar[tuple[RuleSize, ...]] = (
        RuleSize(5, 3),  # 0
        RuleSize(1, 1),  # 1
        RuleSize(2, 1),  # 2
        RuleSize(3, 2),  # 3
    )

    _charsets: ClassVar[tuple[tuple[int, ...], ...]] = (
        Generator._charset(((0x20, 0x7f), )),  # 0
        Generator._charset(((0x30, 0x3a), )),  # 1
        Generator._charset(((0x41, 0x47), )),  # 2
        Generator._charset(((0x41, 0x5b), (0x61, 0x7b), )),  # 3
        Generator._charset(((0x21, 0x7f), )),  # 4
        Generator._charset(((0x80, 0x100), )),  # 5
    )
